name: Lint (gh-pages)

on:
  push:
    branches:
      - master

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.2.0
      - run: npm ci
      - run: npm run lint
